#!/bin/bash
cnodes=4
max_tries=20

sudo /home/pi/uhubctl/uhubctl -r 4 -a cycle
sudo rpiboot -o -l -d /home/pi/tcboot > /tmp/tcboot.log 2>&1 &
rpiboot_pid=$!
echo "rpiboot started, pid $rpiboot_pid.  Log in /tmp/tcboot.log"
echo "Wait for nodes to boot..."
tries=1
num_alive=0
while [ $num_alive -lt $cnodes ] && [ $tries -le $max_tries ]; do
	sleep 10
	echo -n "Try $tries : "
	num_alive=`pdsh -R ssh -w node[1-4] hostname 2>/dev/null | grep -e "^node" | wc -l`
	echo " $num_alive responding"
	tries=$(( tries + 1 ))
done

sudo kill $rpiboot_pid
